# Progressive: True  -> Advancement
#              False -> Priority
#              None  -> Normal
#    Item:                            (type, Progessive, GetItemID, (Object, Model), special),
item_table = {
    'Bow':                              ('Item',     True,  0x83, (0x00E9, 0x35), None),
    'Progressive Hookshot':             ('Item',     True,  0x80, (0x00DD, 0x2D), None),
    'Hammer':                           ('Item',     True,  0x0D, (0x00F6, 0x41), None),
    'Slingshot':                        ('Item',     True,  0x84, (0x00E7, 0x33), None),
    'Boomerang':                        ('Item',     True,  0x06, (0x00E8, 0x34), None),
    'Bomb Bag':                         ('Item',     True,  0x82, (0x00BF, 0x18), None),
    'Lens of Truth':                    ('Item',     True,  0x0A, (0x00EA, 0x36), None),
    'Dins Fire':                        ('Item',     True,  0x5C, (0x015D, 0x64), None),
    'Farores Wind':                     ('Item',     True,  0x5D, (0x015D, 0x65), None),
    'Nayrus Love':                      ('Item',     True,  0x5E, (0x015D, 0x66), None),
    'Fire Arrows':                      ('Item',     True,  0x58, (0x0158, 0x60), None),
    'Ice Arrows':                       ('Item',     True,  0x59, (0x0158, 0x61), None),
    'Light Arrows':                     ('Item',     True,  0x5A, (0x0158, 0x62), None),
    #'Fairy Ocarina':                   ('Item',     True,  0x3B, (0x010E, 0x46), None),
    #'Ocarina of Time':                 ('Item',     True,  0x0C, (0x00DE, 0x2F), None),
    'Ocarina':                          ('Item',     True,  0xC3, (0x00DE, 0x2F), None),
    'Bottle':                           ('Item',     True,  0x0F, (0x00C6, 0x01), None),
    'Bottle with Letter':               ('Item',     True,  0x15, (0x010B, 0x45), None),
    'Bottle with Milk':                 ('Item',     True,  0x14, (0x00DF, 0x30), None),
    'Bottle with Red Potion':           ('Item',     True,  0x89, (0x00C6, 0x01), None),
    'Bottle with Green Potion':         ('Item',     True,  0x8A, (0x00C6, 0x01), None),
    'Bottle with Blue Potion':          ('Item',     True,  0x8B, (0x00C6, 0x01), None),
    'Bottle with Fairy':                ('Item',     True,  0x8C, (0x00C6, 0x01), None),
    'Bottle with Fish':                 ('Item',     True,  0x8D, (0x00C6, 0x01), None),
    'Bottle with Blue Fire':            ('Item',     True,  0x8E, (0x00C6, 0x01), None),
    'Bottle with Bugs':                 ('Item',     True,  0x8F, (0x00C6, 0x01), None),
    'Bottle with Big Poe':              ('Item',     True,  0x90, (0x00C6, 0x01), None),
    'Bottle with Poe':                  ('Item',     True,  0x91, (0x00C6, 0x01), None),
    'Weird Egg':                        ('Item',     True,  0x47, (0x00DA, 0x29), None),
    'Pocket Egg':                       ('Item',     True,  0x1D, (0x00DA, 0x29), None),
    'Pocket Cucco':                     ('Item',     True,  0x1E, (0x0109, 0x44), None),
    'Cojiro':                           ('Item',     True,  0x0E, (0x0109, 0x5E), None),
    'Odd Mushroom':                     ('Item',     True,  0x1F, (0x0141, 0x54), None),
    'Odd Potion':                       ('Item',     True,  0x20, (0x0140, 0x53), None),
    'Poachers Saw':                     ('Item',     True,  0x21, (0x00F5, 0x40), None),
    'Broken Sword':                     ('Item',     True,  0x22, (0x0143, 0x56), None),
    'Prescription':                     ('Item',     True,  0x23, (0x0146, 0x57), None),
    'Eyeball Frog':                     ('Item',     True,  0x24, (0x0149, 0x5A), None),
    'Eyedrops':                         ('Item',     True,  0x25, (0x013F, 0x52), None),
    'Claim Check':                      ('Item',     True,  0x26, (0x0142, 0x55), None),
    'Kokiri Sword':                     ('Item',     True,  0x27, (0x018D, 0x74), None),
    'Master Sword':                     ('Item',     True,  None, (None,   None), None),
    'Biggoron Sword':                   ('Item',     True,  0xB5, (0x00F8, 0x43), None),
    'Deku Shield':                      ('Item',     None,  0xD2, (0x00CB, 0x1D), None),
    'Hylian Shield':                    ('Item',     None,  0xD3, (0x00DC, 0x2C), None),
    'Mirror Shield':                    ('Item',     True,  0x2B, (0x00EE, 0x3A), None),
    'Goron Tunic':                      ('Item',     True,  0x2C, (0x00F2, 0x3C), None),
    'Zora Tunic':                       ('Item',     True,  0x2D, (0x00F2, 0x3D), None),
    'Iron Boots':                       ('Item',     True,  0x2E, (0x0118, 0x47), None),
    'Hover Boots':                      ('Item',     True,  0x2F, (0x0157, 0x5F), None),
    'Progressive Strength Upgrade':     ('Item',     True,  0x81, (0x0147, 0x58), None),
    'Progressive Scale':                ('Item',     True,  0x86, (0x00DB, 0x2A), None),
    'Progressive Wallet':               ('Item',     True,  0x85, (0x00D1, 0x22), None),
    'Deku Stick Capacity':              ('Item',     None,  0x88, (0x00C7, 0x1B), None),
    'Deku Nut Capacity':                ('Item',     None,  0x87, (0x00BB, 0x12), None),
    'Magic Meter':                      ('Item',     True,  0xC0, (0x00CD, 0x1E), None),
    'Double Defense':                   ('Item',     True,  0xBF, (0x00BD, 0x13), None),
    'Stone of Agony':                   ('Item',     True,  0x39, (0x00C8, 0x21), None),
    'Piece of Heart':                   ('Item',     None,  0x3E, (0x00BD, 0x14), None),
    'Heart Container':                  ('Item',     None,  0x3D, (0x00BD, 0x13), None),
    'Piece of Heart (Treasure Chest Game)': ('Item', None,  0x76, (0x00BD, 0x14), None),
    'Heart Container (Boss)':           ('Item',     None,  0x4F, (0x00BD, 0x13), None),
    'Recovery Heart':                   ('Item',     None,  0xB6, (0x00B7, 0x09), None),
    'Arrows (5)':                       ('Item',     None,  0xB7, (0x00D8, 0x25), None),
    'Arrows (10)':                      ('Item',     None,  0xB8, (0x00D8, 0x26), None),
    'Arrows (30)':                      ('Item',     None,  0xB9, (0x00D8, 0x27), None),
    'Bombs (5)':                        ('Item',     None,  0xBA, (0x00CE, 0x20), None),
    'Bombs (10)':                       ('Item',     None,  0xBB, (0x00CE, 0x20), None),
    'Bombs (20)':                       ('Item',     None,  0xBC, (0x00CE, 0x20), None),
    'Bombchus (5)':                     ('Item',     True,  0x6A, (0x00D9, 0x28), None),
    'Bombchus (10)':                    ('Item',     True,  0x03, (0x00D9, 0x28), None),
    'Bombchus (20)':                    ('Item',     True,  0x6B, (0x00D9, 0x28), None),
    'Bombchus':                         ('Item',     True,  0xC2, (0x00D9, 0x28), None),
    'Deku Nuts (5)':                    ('Item',     None,  0xBD, (0x00BB, 0x12), None),
    'Deku Nuts (10)':                   ('Item',     None,  0xBE, (0x00BB, 0x12), None),
    'Deku Stick (1)':                   ('Item',     None,  0xD0, (0x00C7, 0x1B), None),
    'Deku Seeds (30)':                  ('Item',     None,  0xD1, (0x0119, 0x48), None),
    'Rupee (Treasure Chest Game)':      ('Item',     None,  0x72, (0x017F, 0x6D), None),
    'Rupee (1)':                        ('Item',     None,  0x4C, (0x017F, 0x6D), None),
    'Rupees (5)':                       ('Item',     None,  0x4D, (0x017F, 0x6E), None),
    'Rupees (20)':                      ('Item',     None,  0x4E, (0x017F, 0x6F), None),
    'Rupees (50)':                      ('Item',     None,  0x55, (0x017F, 0x71), None),
    'Rupees (200)':                     ('Item',     None,  0x56, (0x017F, 0x72), None),
    'Skull Mask':                       ('Item',     None,  0x17, (0x0136, 0x4F), None),
    'Spooky Mask':                      ('Item',     None,  0x18, (0x0135, 0x32), None),
    'Keaton Mask':                      ('Item',     None,  0x1A, (0x0134, 0x31), None),
    'Bunny Hood':                       ('Item',     None,  0x1B, (0x0137, 0x50), None),
    'Mask of Truth':                    ('Item',     None,  0x1C, (0x0138, 0x51), None),
    'Goron Mask':                       ('Item',     None,  0x51, (0x0150, 0x5B), None),
    'Zora Mask':                        ('Item',     None,  0x52, (0x0151, 0x5C), None),
    'Gerudo Mask':                      ('Item',     None,  0x53, (0x0152, 0x5D), None),
    'Ice Trap':                         ('Item',     False, 0x7C, (None,   None), None),
    'Magic Bean':                       ('Item',     True,  0x16, (0x00F3, 0x3E), None),
    'Zeldas Letter':                    ('Item',     True,  None, (None,   None), None),
    'Gerudo Membership Card':           ('Item',     True,  0x3A, (0x00D7, 0x24), None),
    'Boss Key':                         ('BossKey',  True,  0x3F, (0x00B9, 0x0A), None),
    'Boss Key (Forest Temple)':         ('BossKey',  True,  0x92, (0x00B9, 0x0A), None),
    'Boss Key (Fire Temple)':           ('BossKey',  True,  0x93, (0x00B9, 0x0A), None),
    'Boss Key (Water Temple)':          ('BossKey',  True,  0x94, (0x00B9, 0x0A), None),
    'Boss Key (Spirit Temple)':         ('BossKey',  True,  0x95, (0x00B9, 0x0A), None),
    'Boss Key (Shadow Temple)':         ('BossKey',  True,  0x96, (0x00B9, 0x0A), None),
    'Boss Key (Ganons Castle)':         ('BossKey',  True,  0x97, (0x00B9, 0x0A), None),
    'Compass':                          ('Compass',  None,  0x40, (0x00B8, 0x0B), None),
    'Compass (Deku Tree)':              ('Compass',  None,  0x98, (0x00B8, 0x0B), None),
    'Compass (Dodongos Cavern)':        ('Compass',  None,  0x99, (0x00B8, 0x0B), None),
    'Compass (Jabu Jabus Belly)':       ('Compass',  None,  0x9A, (0x00B8, 0x0B), None),
    'Compass (Forest Temple)':          ('Compass',  None,  0x9B, (0x00B8, 0x0B), None),
    'Compass (Fire Temple)':            ('Compass',  None,  0x9C, (0x00B8, 0x0B), None),
    'Compass (Water Temple)':           ('Compass',  None,  0x9D, (0x00B8, 0x0B), None),
    'Compass (Spirit Temple)':          ('Compass',  None,  0x9E, (0x00B8, 0x0B), None),
    'Compass (Shadow Temple)':          ('Compass',  None,  0x9F, (0x00B8, 0x0B), None),
    'Compass (Bottom of the Well)':     ('Compass',  None,  0xA0, (0x00B8, 0x0B), None),
    'Compass (Ice Cavern)':             ('Compass',  None,  0xA1, (0x00B8, 0x0B), None),
    'Map':                              ('Map',      None,  0x41, (0x00C8, 0x1C), None),
    'Map (Deku Tree)':                  ('Map',      None,  0xA2, (0x00C8, 0x1C), None),
    'Map (Dodongos Cavern)':            ('Map',      None,  0xA3, (0x00C8, 0x1C), None),
    'Map (Jabu Jabus Belly)':           ('Map',      None,  0xA4, (0x00C8, 0x1C), None),
    'Map (Forest Temple)':              ('Map',      None,  0xA5, (0x00C8, 0x1C), None),
    'Map (Fire Temple)':                ('Map',      None,  0xA6, (0x00C8, 0x1C), None),
    'Map (Water Temple)':               ('Map',      None,  0xA7, (0x00C8, 0x1C), None),
    'Map (Spirit Temple)':              ('Map',      None,  0xA8, (0x00C8, 0x1C), None),
    'Map (Shadow Temple)':              ('Map',      None,  0xA9, (0x00C8, 0x1C), None),
    'Map (Bottom of the Well)':         ('Map',      None,  0xAA, (0x00C8, 0x1C), None),
    'Map (Ice Cavern)':                 ('Map',      None,  0xAB, (0x00C8, 0x1C), None),
    'Small Key':                        ('SmallKey', True,  0x42, (0x00AA, 0x02), None),
    'Small Key (Forest Temple)':        ('SmallKey', True,  0xAC, (0x00AA, 0x02), None),
    'Small Key (Fire Temple)':          ('SmallKey', True,  0xAD, (0x00AA, 0x02), None),
    'Small Key (Water Temple)':         ('SmallKey', True,  0xAE, (0x00AA, 0x02), None),
    'Small Key (Spirit Temple)':        ('SmallKey', True,  0xAF, (0x00AA, 0x02), None),
    'Small Key (Shadow Temple)':        ('SmallKey', True,  0xB0, (0x00AA, 0x02), None),
    'Small Key (Bottom of the Well)':   ('SmallKey', True,  0xB1, (0x00AA, 0x02), None),
    'Small Key (Gerudo Training Grounds)':('SmallKey',True, 0xB2, (0x00AA, 0x02), None),
    'Small Key (Ganons Castle)':        ('SmallKey', True,  0xB4, (0x00AA, 0x02), None),
    'Small Key (Gerudo Fortress)':('FortressSmallKey',True, 0xB3, (0x00AA, 0x02), None),
    'Gold Skulltula Token':             ('Token',    True,  0x5B, (0x015C, 0x63), None),
    'Epona':                            ('Event',    True,  None, (None,   None), None),
    'Deku Stick Drop':                  ('Event',    True,  None, (None,   None), None),
    'Deku Nut Drop':                    ('Event',    True,  None, (None,   None), None),
    'Carpenter Rescue':                 ('Event',    True,  None, (None,   None), None),
    'Forest Trial Clear':               ('Event',    True,  None, (None,   None), None),
    'Fire Trial Clear':                 ('Event',    True,  None, (None,   None), None),
    'Water Trial Clear':                ('Event',    True,  None, (None,   None), None),
    'Shadow Trial Clear':               ('Event',    True,  None, (None,   None), None),
    'Spirit Trial Clear':               ('Event',    True,  None, (None,   None), None),
    'Light Trial Clear':                ('Event',    True,  None, (None,   None), None),
    'Triforce':                         ('Event',    True,  None, (None,   None), None),
    'Buy Deku Nut (5)':                 ('Shop',     True,  0x00, (0x00BB, 0x12), {'price': 15}),
    'Buy Arrows (30)':                  ('Shop',     False, 0x01, (0x00D8, 0x26), {'price': 60}),
    'Buy Arrows (50)':                  ('Shop',     False, 0x02, (0x00D8, 0x27), {'price': 90}),
    'Buy Bombs (5) [25]':               ('Shop',     False, 0x03, (0x00CE, 0x20), {'price': 25}),
    'Buy Deku Nut (10)':                ('Shop',     True,  0x04, (0x00BB, 0x12), {'price': 30}),
    'Buy Deku Stick (1)':               ('Shop',     True,  0x05, (0x00C7, 0x1B), {'price': 10}),
    'Buy Bombs (10)':                   ('Shop',     False, 0x06, (0x00CE, 0x20), {'price': 50}),
    'Buy Fish':                         ('Shop',     False, 0x07, (0x00F4, 0x3F), {'price': 200}),
    'Buy Red Potion [30]':              ('Shop',     False, 0x08, (0x00EB, 0x38), {'price': 30}),
    'Buy Green Potion':                 ('Shop',     False, 0x09, (0x00EB, 0x37), {'price': 30}),
    'Buy Blue Potion':                  ('Shop',     False, 0x0A, (0x00EB, 0x39), {'price': 100}),
    'Buy Hylian Shield':                ('Shop',     False, 0x0C, (0x00DC, 0x2C), {'price': 80}),
    'Buy Deku Shield':                  ('Shop',     True,  0x0D, (0x00CB, 0x1D), {'price': 40}),
    'Buy Goron Tunic':                  ('Shop',     True,  0x0E, (0x00F2, 0x3C), {'price': 200}),
    'Buy Zora Tunic':                   ('Shop',     True,  0x0F, (0x00F2, 0x3D), {'price': 300}),
    'Buy Heart':                        ('Shop',     False, 0x10, (0x00B7, 0x09), {'price': 10}),
    'Buy Bombchu (10)':                 ('Shop',     True,  0x15, (0x00D9, 0x28), {'price': 99}),
    'Buy Bombchu (20)':                 ('Shop',     True,  0x16, (0x00D9, 0x28), {'price': 180}),
    'Buy Bombchu (5)':                  ('Shop',     True,  0x18, (0x00D9, 0x28), {'price': 60}),
    'Buy Deku Seeds (30)':              ('Shop',     False, 0x1D, (0x0119, 0x48), {'price': 30}),
    'Sold Out':                         ('Shop',     False, 0x26, (0x0148, 0x59), None),
    'Buy Blue Fire':                    ('Shop',     True,  0x27, (0x0173, 0x67), {'price': 300}),
    'Buy Bottle Bug':                   ('Shop',     True,  0x28, (0x0174, 0x68), {'price': 50}),
    'Buy Poe':                          ('Shop',     False, 0x2A, (0x0176, 0x6A), {'price': 30}),
    'Buy Fairy\'s Spirit':              ('Shop',     False, 0x2B, (0x0177, 0x6B), {'price': 50}),
    'Buy Arrows (10)':                  ('Shop',     False, 0x2C, (0x00D8, 0x25), {'price': 20}),
    'Buy Bombs (20)':                   ('Shop',     False, 0x2D, (0x00CE, 0x20), {'price': 80}),
    'Buy Bombs (30)':                   ('Shop',     False, 0x2E, (0x00CE, 0x20), {'price': 120}),
    'Buy Bombs (5) [35]':               ('Shop',     False, 0x2F, (0x00CE, 0x20), {'price': 35}),
    'Buy Red Potion [40]':              ('Shop',     False, 0x30, (0x00EB, 0x38), {'price': 40}),
    'Buy Red Potion [50]':              ('Shop',     False, 0x31, (0x00EB, 0x38), {'price': 50}),

    'Zeldas Lullaby':                   ('Song',     True,  0xCA, (0x00B6, 0x04), 
                                            {
                                                'text_id': 0xD4,
                                                'song_id': 0x0A, 
                                                'item_id': 0x60,
                                            }),
    'Eponas Song':                      ('Song',     True,  0xCB, (0x00B6, 0x06),
                                            {
                                                'text_id': 0xD2,
                                                'song_id': 0x09, 
                                                'item_id': 0x61,
                                            }),
    'Suns Song':                        ('Song',     True,  0xCD, (0x00B6, 0x08),
                                            {
                                                'text_id': 0xD3,
                                                'song_id': 0x0B, 
                                                'item_id': 0x63,
                                            }),
    'Sarias Song':                      ('Song',     True,  0xCC, (0x00B6, 0x03),
                                            {
                                                'text_id': 0xD1,
                                                'song_id': 0x08, 
                                                'item_id': 0x62,
                                            }),
    'Song of Time':                     ('Song',     True,  0xCE, (0x00B6, 0x05),
                                            {
                                                'text_id': 0xD5,
                                                'song_id': 0x0C, 
                                                'item_id': 0x64,
                                            }),
    'Song of Storms':                   ('Song',     True,  0xCF, (0x00B6, 0x07),
                                            {
                                                'text_id': 0xD6,
                                                'song_id': 0x0D, 
                                                'item_id': 0x65,
                                            }),
    'Minuet of Forest':                 ('Song',     True,  0xC4, (0x00B6, 0x03),
                                            {
                                                'text_id': 0x73,
                                                'song_id': 0x02, 
                                                'item_id': 0x5A,
                                            }),
    'Prelude of Light':                 ('Song',     True,  0xC9, (0x00B6, 0x08),
                                            {
                                                'text_id': 0x78,
                                                'song_id': 0x07, 
                                                'item_id': 0x5F,
                                            }),
    'Bolero of Fire':                   ('Song',     True,  0xC5, (0x00B6, 0x04),
                                            {
                                                'text_id': 0x74,
                                                'song_id': 0x03, 
                                                'item_id': 0x5B,
                                            }),
    'Serenade of Water':                ('Song',     True,  0xC6, (0x00B6, 0x05),
                                            {
                                                'text_id': 0x75,
                                                'song_id': 0x04, 
                                                'item_id': 0x5C,
                                            }),
    'Nocturne of Shadow':               ('Song',     True,  0xC8, (0x00B6, 0x07),
                                            {
                                                'text_id': 0x77,
                                                'song_id': 0x06, 
                                                'item_id': 0x5E,
                                            }),
    'Requiem of Spirit':                ('Song',     True,  0xC7, (0x00B6, 0x08),
                                            {
                                                'text_id': 0x76,
                                                'song_id': 0x05, 
                                                'item_id': 0x5D,
                                            }),

    'Kokiri Emerald':                   ('Event',    True,  None, (None,   None), 
                                            {
                                                'save_byte':  0xA5,
                                                'save_bit':   0x04,
                                                'addr2_data': 0x80,
                                                'bit_mask':   0x00040000,
                                                'item_id':    0x6C,
                                            }),
    'Goron Ruby':                       ('Event',    True,  None, (None,   None), 
                                            {
                                                'save_byte':  0xA5,
                                                'save_bit':   0x08,
                                                'addr2_data': 0x81,
                                                'bit_mask':   0x00080000,
                                                'item_id':    0x6D,
                                            }),
    'Zora Sapphire':                    ('Event',    True,  None, (None,   None), 
                                            {
                                                'save_byte':  0xA5,
                                                'save_bit':   0x10,
                                                'addr2_data': 0x82,
                                                'bit_mask':   0x00100000,
                                                'item_id':    0x6E,
                                            }),
    'Forest Medallion':                 ('Event',    True,  None, (None,   None), 
                                            {
                                                'save_byte':  0xA7,
                                                'save_bit':   0x01,
                                                'addr2_data': 0x3E,
                                                'bit_mask':   0x00000001,
                                                'item_id':    0x66,
                                            }),
    'Fire Medallion':                   ('Event',    True,  None, (None,   None), 
                                            {
                                                'save_byte':  0xA7,
                                                'save_bit':   0x02,
                                                'addr2_data': 0x3C,
                                                'bit_mask':   0x00000002,
                                                'item_id':    0x67,
                                            }),
    'Water Medallion':                  ('Event',    True,  None, (None,   None), 
                                            {
                                                'save_byte':  0xA7,
                                                'save_bit':   0x04,
                                                'addr2_data': 0x3D,
                                                'bit_mask':   0x00000004,
                                                'item_id':    0x68,
                                            }),
    'Spirit Medallion':                 ('Event',    True,  None, (None,   None), 
                                            {
                                                'save_byte':  0xA7,
                                                'save_bit':   0x08,
                                                'addr2_data': 0x3F,
                                                'bit_mask':   0x00000008,
                                                'item_id':    0x69,
                                            }),
    'Shadow Medallion':                 ('Event',    True,  None, (None,   None), 
                                            {
                                                'save_byte':  0xA7,
                                                'save_bit':   0x10,
                                                'addr2_data': 0x41,
                                                'bit_mask':   0x00000010,
                                                'item_id':    0x6A,
                                            }),
    'Light Medallion':                  ('Event',    True,  None, (None,   None), 
                                            {
                                                'save_byte':  0xA7,
                                                'save_bit':   0x20,
                                                'addr2_data': 0x40,
                                                'bit_mask':   0x00000020,
                                                'item_id':    0x6B,
                                            }),
}

